# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_url', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_url', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('id_token', models.CharField(blank=True, max_length=1200, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesforce_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('OP', 'Opportunity')], max_length=2)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesforce.SalesforceCredential')),
            ],
        ),
    ]
