# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('access_token_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesforce_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
