export const INSTRUCTION_CREATING = 'INSTRUCTION_CREATING'
export const INSTRUCTION_CREATE_SUCCESS = 'INSTRUCTION_CREATE_SUCCESS'
export const INSTRUCTION_CREATE_ERROR = 'INSTRUCTION_CREATE_ERROR'

export const INSTRUCTION_REQUESTING = 'INSTRUCTION_REQUESTING'
export const INSTRUCTION_REQUEST_SUCCESS = 'INSTRUCTION_REQUEST_SUCCESS'
export const INSTRUCTION_REQUEST_ERROR = 'INSTRUCTION_REQUEST_ERROR'
