export const SALESFORCE_AUTH_REQUESTING = 'INSTRUCTION_REQUESTING'
export const SALESFORCE_AUTH_REQUEST_SUCCESS = 'INSTRUCTION_REQUEST_SUCCESS'
export const SALESFORCE_AUTH_REQUEST_ERROR = 'INSTRUCTION_REQUEST_ERROR'
