export const SALESFORCE_AUTH_REQUESTING = 'AUTH_REQUESTING'
export const SALESFORCE_AUTH_REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS'
export const SALESFORCE_AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR'
export const SALESFORCE_AUTH_CREATING = 'AUTH_CREATING'
